name: Test
on:
  workflow_call:

jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls
      - run: pwd
      - run: cd src && ls
